### ISSUE TITLE
[BUG] (possible) undefined configENABLE_PAC

### ISSUE THREAD

**Issue by scaprile** [FreeRTOS/FreeRTOS-Kernel#1293]
Arm Cortex-M33 NTZ project working with 11.1.0 fails to build on 11.2.0
FreeRTOS.h includes portable.h
portable.h includes portmacro.h (`portENTER_CRITICAL` is not defined)
https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/0adc196d4bd52a2d91102b525b0aafc1e14a2386/include/portable.h#L52-L55
portmacro.h includes portmacrocommon.h
portmacrocommon.h refers to + configENABLE_PAC+ 
https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/0adc196d4bd52a2d91102b525b0aafc1e14a2386/portable/GCC/ARM_CM33_NTZ/non_secure/portmacrocommon.h#L131
but this is only defined in FreeRTOS.h 3000 lines below
https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/0adc196d4bd52a2d91102b525b0aafc1e14a2386/include/FreeRTOS.h#L3045-L3047

We build with `-Werror` so this breaks compilation:
```
In file included from FreeRTOS-Kernel/portable/GCC/ARM_CM33_NTZ/non_secure/portmacro.h:58,
                 from FreeRTOS-Kernel/include/portable.h:53,
                 from FreeRTOS-Kernel/include/FreeRTOS.h:108,
                 from FreeRTOS-Kernel/timers.c:37:
FreeRTOS-Kernel/portable/GCC/ARM_CM33_NTZ/non_secure/portmacrocommon.h:131:7: error: "configENABLE_PAC" is not defined, evaluates to 0 [-Werror=undef]
  131 | #if ( configENABLE_PAC == 1 )
      |       ^~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```
